export const nameList = [
  "Video.Sckre",
  "Lukas Lundberg",
  "Bezz Walls",
  "Ziggy",
  "Disey",
  "Bob Horrors",
  "HUGE!",
  "Ollio",
  "Salla Vartiainen",
  "Alex Delarge",
  "Karin Söderquist",
  "Holem",
  "Kiss",
  "Korallpionen",
  "Anders Reventlov",
  "Nino Come",
  "Dotsy",
  "Liam Bononi",
  "Herr Nilsson",
  "African Ginger",
  "Stfi",
  "Anis",
  "Vejam",
  "Miguel Afa",
  "Mind",
  "Pencil",
  "Hagsepeesy",
  "Leon",
  "Ligisd",
  "Danny Reveco",
  "Omatics",
  "The Highness",
  "Kcr_kocur",
  "Mathis Anvik",
  "Adam Gust",
  "Marcin Błach",
  "Azit",
  "Joakim Hansén",
  "Adrian Platkovsky",
  "Greta Abeni",
  "Diego Fustar",
  "Valeria Rizzo",
  "Peter Birk",
  "Galletamaria",
  "Anya Blom",
  "John Beijer",
  "Björk Hijoort",
  "Roid",
  "Hop Louie",
  "Änna",
  "Komendanttt",
  "Guido Palmadessa",
  "Toms",
  "Sagie",
];
